package com.growit.api.domain;

public enum  LoanStatus {
    DRAFTED_ON_CALCULATOR, ON_FUNDING, ISSUED, FULLY_RETURNED, RETURNED_ON_GRACE_PERIOD, PARTIALLY_RETURNED, SOLD_TO_ANOTHER_INVESTOR,
    SOLD_TO_COLLECTOR, DELAYED, ON_GRACE_PERIOD, SIX_TO_14_DAYS_LATE, FIFTEEN_TO_31_DAYS_LATE,
    THIRTY_TWO_TO_120_DAYS_LATE, CHARGED_OFF
}
